# Generated by Django 3.2.5 on 2021-08-20 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('number', models.IntegerField()),
                ('stationName', models.TextField(max_length=50)),
                ('stationLocation', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LockerUsing',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('lockerIdx', models.IntegerField()),
                ('password', models.TextField()),
                ('title', models.TextField()),
                ('info', models.TextField(null=True)),
                ('isOpen', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trusterId', models.TextField()),
                ('isPaid', models.BooleanField()),
            ],
        ),
    ]
