# Generated by Django 3.2.5 on 2021-08-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LockerUsing',
            new_name='OccupiedLocker',
        ),
    ]
