# Generated by Django 3.2.5 on 2021-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('userPw', models.TextField()),
                ('autoPayment', models.BooleanField()),
            ],
        ),
    ]
